# 避免 M1 架構產生不相容的 object 檔，我們透過 docker 執行
DOCKER_CMD = docker run --rm -v $(PWD):/workspace -w /workspace os-builder

all: build-env myos.bin

build-env:
	docker build -t os-builder .

myos.bin: boot.o
	$(DOCKER_CMD) ld -n -T linker.ld -o myos.bin boot.o

boot.o: boot.S
	$(DOCKER_CMD) nasm -f elf32 boot.S -o boot.o

clean:
	rm -f *.o *.bin
